var fs = require('fs');
var CodeSamples = {
    Icon: fs.readFileSync(__dirname + '/../CodeSamples/Icon.js', 'utf8'),
    DefaultNavMenu: fs.readFileSync(__dirname + '/../CodeSamples/NavMenu.js', 'utf8'),
    DefaultButton: fs.readFileSync(__dirname + '/../CodeSamples/DefaultButton.js', 'utf8'),
    ButtonToolbar: fs.readFileSync(__dirname + '/../CodeSamples/ButtonToolbar.js', 'utf8'),
    StateButton: fs.readFileSync(__dirname + '/../CodeSamples/StateButton.js', 'utf8'),
    DisabledButton: fs.readFileSync(__dirname + '/../CodeSamples/DisabledButton.js', 'utf8'),
    BasicGrid: fs.readFileSync(__dirname + '/../CodeSamples/BasicGrid.js', 'utf8'),
    Tabs: fs.readFileSync(__dirname + '/../CodeSamples/Tabs.js', 'utf8'),
    DefaultLink: fs.readFileSync(__dirname + '/../CodeSamples/DefaultLink.js', 'utf8'),
    GoldLink: fs.readFileSync(__dirname + '/../CodeSamples/GoldLink.js', 'utf8'),
    GreyLink: fs.readFileSync(__dirname + '/../CodeSamples/GreyLink.js', 'utf8'),
    DefaultLabel: fs.readFileSync(__dirname + '/../CodeSamples/DefaultLabel.js', 'utf8'),
    DefaultList: fs.readFileSync(__dirname + '/../CodeSamples/DefaultList.js', 'utf8'),
    Spinner: fs.readFileSync(__dirname + '/../CodeSamples/Spinner.js', 'utf8'),
    TextBox: fs.readFileSync(__dirname + '/../CodeSamples/TextBox.js', 'utf8'),
    MultilineTextBox: fs.readFileSync(__dirname + '/../CodeSamples/MultilineTextBox.js', 'utf8'),
    TextBoxInForm: fs.readFileSync(__dirname + '/../CodeSamples/TextBoxInForm.js', 'utf8'),
    Radio: fs.readFileSync(__dirname + '/../CodeSamples/Radio.js', 'utf8'),
    RadioGroup: fs.readFileSync(__dirname + '/../CodeSamples/RadioGroup.js', 'utf8'),
    DropdownList: fs.readFileSync(__dirname + '/../CodeSamples/DropdownList.js', 'utf8'),
    Pager: fs.readFileSync(__dirname + '/../CodeSamples/Pager.js', 'utf8'),
    Modal: fs.readFileSync(__dirname + '/../CodeSamples/Modal.js', 'utf8'),
    CheckBox: {
        Default: fs.readFileSync(__dirname + '/../CodeSamples/CheckBox/default.js', 'utf8'),
        Disabled: fs.readFileSync(__dirname + '/../CodeSamples/CheckBox/disabled.js', 'utf8'),
        Readonly: fs.readFileSync(__dirname + '/../CodeSamples/CheckBox/readonly.js', 'utf8')
    },
    Table: fs.readFileSync(__dirname + '/../CodeSamples/Table.js', 'utf8'),
    TableObjectData: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableObjectData.js', 'utf8'),
    TableLockedColumn: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableLockedColumn.js', 'utf8'),
    TableRowGrouping: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableRowGrouping.js', 'utf8'),
    TableCellHtml: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableCellHtml.js', 'utf8'),
    TableCallback: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableCallback.js', 'utf8'),
    TableFixedHeader: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableFixedHeader.js', 'utf8'),
    SimpleTable: fs.readFileSync(__dirname + '/../CodeSamples/Table/SimpleTable.js', 'utf8'),
    AdvancedTable: fs.readFileSync(__dirname + '/../CodeSamples/Table/AdvancedTable.js', 'utf8'),
    TableCustomComponentInCell: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableCustomComponentInCell.js', 'utf8'),
    TableSortField: fs.readFileSync(__dirname + '/../CodeSamples/Table/TableSortField.js', 'utf8'),
    DateInput: fs.readFileSync(__dirname + '/../CodeSamples/DateInput.js', 'utf8'),
    Accordion: fs.readFileSync(__dirname + '/../CodeSamples/Accordion.js', 'utf8'),
    Panel: fs.readFileSync(__dirname + '/../CodeSamples/Panel.js', 'utf8'),
    PanelGroup: fs.readFileSync(__dirname + '/../CodeSamples/PanelGroup.js', 'utf8'),
    Drawers: fs.readFileSync(__dirname + '/../CodeSamples/Drawers.js', 'utf8'),
    Typeahead: fs.readFileSync(__dirname + '/../CodeSamples/Typeahead.js', 'utf8'),
    TypeaheadServer: fs.readFileSync(__dirname + '/../CodeSamples/TypeaheadServer.js', 'utf8'),
    TypeaheadCustomRender: fs.readFileSync(__dirname + '/../CodeSamples/TypeaheadCustomRender.js', 'utf8'),
    DefaultPopover: fs.readFileSync(__dirname + '/../CodeSamples/DefaultPopover.js', 'utf8'),
    TextPopover: fs.readFileSync(__dirname + '/../CodeSamples/TextPopover.js', 'utf8'),
    IconPopover: fs.readFileSync(__dirname + '/../CodeSamples/IconPopover.js', 'utf8'),
    Tree: fs.readFileSync(__dirname + '/../CodeSamples/Tree.js', 'utf8'),
    TreeCheckbox: fs.readFileSync(__dirname + '/../CodeSamples/TreeCheckbox.js', 'utf8'),
    TreeCheckboxCustom: fs.readFileSync(__dirname + '/../CodeSamples/TreeCheckboxCustom.js', 'utf8'),
    MultiDropdown: fs.readFileSync(__dirname + '/../CodeSamples/MultiDropdown.js', 'utf8'),
    ToggleButton: fs.readFileSync(__dirname + '/../CodeSamples/ToggleButton.js', 'utf8'),
    DefaultButtonGroup: fs.readFileSync(__dirname + '/../CodeSamples/ButtonGroup/DefaultButtonGroup.js', 'utf8'),
    ButtonGroupAPI: fs.readFileSync(__dirname + '/../CodeSamples/ButtonGroup/ButtonGroupAPI.js', 'utf8'),
    LiteTableSample: fs.readFileSync(__dirname + '/../CodeSamples/Table/LiteTable.js', 'utf8'),
    ReactTable: fs.readFileSync(__dirname + '/../CodeSamples/ReactTable/SimpleReactTable.js', 'utf8'),
    ReactDragTable: fs.readFileSync(__dirname + '/../CodeSamples/ReactTable/DragReactTable.js', 'utf8'),
    ReactSortTable: fs.readFileSync(__dirname + '/../CodeSamples/ReactTable/SortReactTable.js', 'utf8'),
    LiteTableTreeViewSample: fs.readFileSync(__dirname + '/../CodeSamples/Table/LiteTableTreeView.js', 'utf8'),
    BasicDrillDown: fs.readFileSync(__dirname + '/../CodeSamples/DrillDown/basic.js', 'utf8'),
    AVGDrillDown: fs.readFileSync(__dirname + '/../CodeSamples/DrillDown/avgStyle.js', 'utf8'),
    ComboBox: fs.readFileSync(__dirname + '/../CodeSamples/ComboBox.js', 'utf8'),
    TreeReactTable: fs.readFileSync(__dirname + '/../CodeSamples/ReactTable/TreeReactTable.js', 'utf8'),
    AlertBanner: fs.readFileSync(__dirname + '/../CodeSamples/AlertBanner.js', 'utf8'),
    AdvancedAlertBanner: fs.readFileSync(__dirname + '/../CodeSamples/AdvancedAlertBanner.js', 'utf8'),
    DefaultTooltip: fs.readFileSync(__dirname + '/../CodeSamples/DefaultTooltip.js', 'utf8'),
    ModalAlertBanner: fs.readFileSync(__dirname + '/../CodeSamples/ModalAlertBanner.js', 'utf8'),
    Dropdown: {
        Default: fs.readFileSync(__dirname + '/../CodeSamples/Dropdown/default.js', 'utf8'),
        Multiselect: fs.readFileSync(__dirname + '/../CodeSamples/Dropdown/multiselect.js', 'utf8'),
        MultiselectControlled: fs.readFileSync(__dirname + '/../CodeSamples/Dropdown/multiselect-controlled.js', 'utf8'),
        Searchable: fs.readFileSync(__dirname + '/../CodeSamples/Dropdown/searchable.js', 'utf8'),
        SearchableMultiselect: fs.readFileSync(__dirname + '/../CodeSamples/Dropdown/searchable-multiselect.js', 'utf8')
    },
    TooltipsPopover: fs.readFileSync(__dirname + '/../CodeSamples/TooltipsPopover.js', 'utf8')

};
module.exports = CodeSamples;
